branches:
  only:  # Only build on PRs (or pushes) to master branch.
    - master

sudo: required
services:
  - docker

language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install -r requirements.txt

script:
  - py.test
